# Generated by Django 6.0.5 on 2026-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='🔥 HOT'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='🆕 NEW'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='⭐ POPULAR'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='🏆 TOP'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='course',
            name='students_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество студентов'),
        ),
    ]
