# Generated by Django 6.0.5 on 2026-05-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_hot_course_is_new_course_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='🎁 FREE'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
