# Generated by Django 6.0.5 on 2026-05-09 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Reyting', 'verbose_name_plural': 'Reytinglar'},
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_count',
            field=models.PositiveIntegerField(default=0, verbose_name="O'quvchilar soni"),
        ),
        migrations.AlterField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinglar', to='courses.course'),
        ),
    ]
