# Generated by Django 6.0.5 on 2026-05-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_count',
        ),
        migrations.AlterField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course'),
        ),
    ]
