# Generated by Django 6.0.5 on 2026-05-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_image_remove_course_image_url'),
    ]

    # Legacy conflicting branch. Kept as a no-op so migration graph remains valid.
    operations = []
