# Generated by Django 6.0.5 on 2026-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_image_remove_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_career_path',
            field=models.BooleanField(default=False, verbose_name='🟦 Career path'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_cert_path',
            field=models.BooleanField(default=False, verbose_name='🟨 Certification path'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='🟩 Free course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_skill_path',
            field=models.BooleanField(default=False, verbose_name='🟪 Skill path'),
        ),
    ]
