# Generated by Django 6.0.5 on 2026-05-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_is_career_path_course_is_cert_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='course',
            name='includes_courses',
            field=models.IntegerField(default=1),
        ),
    ]
