# Generated by Django 6.0.5 on 2026-05-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_has_certificate_course_includes_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(default=False, verbose_name='Has certificate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='includes_courses',
            field=models.CharField(max_length=100),
        ),
    ]
