# Generated by Django 6.0.5 on 2026-05-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_has_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='has_certificate',
            field=models.BooleanField(blank=True, default=False, verbose_name='Has certificate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='includes_courses',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
