# Generated by Django 6.0.5 on 2026-05-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_has_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='category')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunSQL(
            """
            UPDATE courses_course
            SET duration = regexp_replace(duration, '[^0-9]', '', 'g')
            WHERE duration IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE courses_course
            SET duration = '1'
            WHERE duration IS NULL OR duration = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE courses_course
            SET includes_courses = regexp_replace(includes_courses, '[^0-9]', '', 'g')
            WHERE includes_courses IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE courses_course
            SET includes_courses = '1'
            WHERE includes_courses IS NULL OR includes_courses = '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            INSERT INTO courses_category (name, slug, is_active)
            SELECT DISTINCT
                category AS name,
                lower(trim(both '-' from regexp_replace(category, '[^a-zA-Z0-9]+', '-', 'g'))) AS slug,
                TRUE AS is_active
            FROM courses_course
            WHERE category IS NOT NULL AND category <> ''
            ON CONFLICT (name) DO NOTHING;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE courses_course AS c
            SET category = cat.id::text
            FROM courses_category AS cat
            WHERE c.category = cat.name;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE courses_course
            SET category = NULL
            WHERE category IS NOT NULL AND category !~ '^[0-9]+$';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='includes_courses',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category'),
        ),
    ]
