# Generated by Django 6.0.5 on 2026-05-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_category_alter_course_duration_and_more'),
    ]

    # `level` exists in the current model and is used by the bot card.
    # Keep this migration as no-op to avoid state conflicts.
    operations = []
