# Generated by Django 6.0.5 on 2026-05-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_category_remove_course_level_course_has_certificate_and_more'),
        ('courses', '0015_remove_course_level'),
    ]

    operations = [
    ]
