# Generated by Django 6.0.5 on 2026-05-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_merge_20260511_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
