# Generated by Django 6.0.5 on 2026-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_course_level_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[("Boshlang'ich", "Boshlang'ich"), ("O'rtacha", "O'rtacha"), ('Murakkab', 'Murakkab')], default='Beginner', max_length=20),
        ),
    ]
