# Generated by Django 6.0.5 on 2026-05-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[("Boshlang'ich", "Boshlang'ich"), ("O'rtacha", "O'rtacha"), ('Murakkab', 'Murakkab')], default="Boshlang'ich", max_length=20),
        ),
    ]
